FROM registry.redhat.io/rhel7/rhel

# set environment
ENV JBOSS_HOME /opt/jboss-eap-7.3
ENV JBOSS_USER=jbosseap
ENV JBOSS_Deploy=webapp.war
ENV EAP_Module /opt/jboss-eap-7.3/modules/com/microsoft/sqlserver
ENV JBOSS_PACKET /opt/jboss-eap-7.3.0.zip

ADD MyRepo.repo /etc/yum.repos.d/MyRepo.repo

# update OS
RUN yum -y update && \
yum -y install sudo openssh-clients telnet unzip java-1.8.0-openjdk-devel && \
yum clean all

# enabling sudo group
# enabling sudo over ssh
RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
sed -i 's/.*requiretty$/Defaults !requiretty/' /etc/sudoers

# Copy the EAP to image, unpack and clean up afterwards
ADD jboss-eap-7.3.0.zip /opt/
RUN unzip -q $JBOSS_PACKET -d /opt/

# Install sqlserver module
RUN mkdir -p ${EAP_Module}/main/
ADD sqljdbc42.jar ${EAP_Module}/main/
ADD module.xml ${EAP_Module}/main/

# add a user for the application, with sudo permissions
RUN groupadd -r $JBOSS_USER -g 433 && \
useradd -u 431 -r -g $JBOSS_USER -d $JBOSS_HOME -s /sbin/nologin -c "$JBOSS_USER user" $JBOSS_USER && \
chown -R $JBOSS_USER:$JBOSS_USER $JBOSS_HOME

# create JBoss console user
RUN $JBOSS_HOME/bin/add-user.sh admin admin --silent && rm -rf ${JBOSS_HOME}/standalone/deployments/*

# configure JBoss
RUN echo "JAVA_OPTS=\"\$JAVA_OPTS -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0\"" >> $JBOSS_HOME/bin/standalone.conf

# set permission folder
RUN chown -R $JBOSS_USER:$JBOSS_USER $JBOSS_HOME

# JBoss ports
EXPOSE 8080 9990 9999

# start JBoss
ENTRYPOINT ${JBOSS_HOME}/bin/standalone.sh -c standalone-full.xml

# deploy app
COPY $JBOSS_Deploy $JBOSS_HOME/standalone/deployments/
RUN chown -R $JBOSS_USER:$JBOSS_USER ${JBOSS_HOME}/standalone/deployments/

USER $JBOSS_USER
CMD /bin/bash
